import { supabase } from "./supabase-client.js";
const app=document.getElementById("adminApp");let products=[];
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));const money=n=>"₹"+Number(n||0).toLocaleString("en-IN");
async function start(){const {data}=await supabase.auth.getSession();if(!data.session)return login();return dashboard(data.session.user)}
function login(){app.innerHTML=`<main class="admin-main"><div class="admin-card" style="max-width:430px;margin:10vh auto"><p class="eyebrow">AURENAR / PRIVATE</p><h1>Admin</h1><form id="login" class="admin-form"><input name="email" type="email" placeholder="Admin email" required><input name="password" type="password" placeholder="Password" required><button>SIGN IN</button><p id="msg" class="muted"></p></form></div></main>`;document.getElementById("login").onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const r=await supabase.auth.signInWithPassword({email:f.get("email"),password:f.get("password")});if(r.error)document.getElementById("msg").textContent=r.error.message;else dashboard(r.data.user)}}
async function dashboard(user){const {data:profile}=await supabase.from("profiles").select("role").eq("id",user.id).single();if(profile?.role!=="admin"){await supabase.auth.signOut();return loginMsg("This account is not an admin.")}app.innerHTML=`<div class="admin-wrap"><header class="admin-top"><a class="wordmark" href="/">AURENAR</a><button id="out">SIGN OUT</button></header><main class="admin-main"><div class="admin-grid"><section class="admin-card"><p class="eyebrow">PRODUCT MANAGEMENT</p><h2>Add piece</h2><form id="form" class="admin-form"><input name="name" placeholder="Product name" required><input name="price" type="number" placeholder="Price ₹" required><input name="image_url" placeholder="Image URL"><input name="category" placeholder="Category (men/women)"><input name="sizes" placeholder="Sizes: S,M,L,XL"><textarea name="description" placeholder="Description"></textarea><label><input name="is_active" type="checkbox" checked> Active</label><button>ADD PRODUCT</button><p id="formMsg" class="muted"></p></form></section><section class="admin-card"><p class="eyebrow">COLLECTION</p><h2>Products</h2><div id="list">Loading…</div></section></div></main></div>`;document.getElementById("out").onclick=()=>supabase.auth.signOut().then(login);document.getElementById("form").onsubmit=addProduct;loadProducts()}
function loginMsg(m){login();setTimeout(()=>{const x=document.getElementById("msg");if(x)x.textContent=m},50)}
async function loadProducts(){const r=await supabase.from("products").select("*").order("created_at",{ascending:false});products=r.data||[];document.getElementById("list").innerHTML=products.map(p=>`<div class="admin-product"><div>${p.image_url?`<img src="${p.image_url}" alt="">`:""}</div><div><strong>${esc(p.name)}</strong><br><span class="muted">${money(p.price)} · ${p.is_active?"ACTIVE":"HIDDEN"}</span></div><button class="danger" data-del="${p.id}">DELETE</button></div>`).join("")||"<p class='muted'>No products yet.</p>";document.querySelectorAll("[data-del]").forEach(b=>b.onclick=async()=>{if(confirm("Delete this product?")){await supabase.from("products").delete().eq("id",b.dataset.del);loadProducts()}})}
async function addProduct(e){e.preventDefault();const f=new FormData(e.target);const row={name:f.get("name"),price:Number(f.get("price")),image_url:f.get("image_url")||null,category:f.get("category")||"men",sizes:String(f.get("sizes")||"S,M,L,XL").split(",").map(x=>x.trim()).filter(Boolean),description:f.get("description")||"",is_active:f.get("is_active")==="on"};const r=await supabase.from("products").insert(row);document.getElementById("formMsg").textContent=r.error?r.error.message:"Added.";if(!r.error){e.target.reset();e.target.is_active.checked=true;loadProducts()}}
start();
