import { supabase } from './supabase-client.js';
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
let editingId=null,products=[];
function safe(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function money(n){return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(n)||0)}function normalizeImages(v){if(Array.isArray(v))return v.filter(Boolean);if(typeof v==='string'){try{const p=JSON.parse(v);return Array.isArray(p)?p.filter(Boolean):[v]}catch{return v.split(/\s*,\s*|\n/).map(x=>x.trim()).filter(Boolean)}}return []}
async function isAdmin(){const {data:{session}}=await supabase.auth.getSession();if(!session)return false;const {data,error}=await supabase.from('profiles').select('role').eq('id',session.user.id).maybeSingle();if(error){console.error(error);return false}return data?.role==='admin'}
function loginView(msg=''){ $('#app').innerHTML=`<main class="admin-shell"><div class="admin-login"><p class="eyebrow">AURENAR / PRIVATE</p><h1>Admin<br>login.</h1><p style="color:#777">Sign in with the existing Supabase admin account. Access is granted only when the authenticated profile has <strong>role = admin</strong>.</p><div class="admin-card"><form class="admin-form" id="loginForm"><label>Email</label><input required name="email" type="email" autocomplete="username"><label>Password</label><input required name="password" type="password" autocomplete="current-password"><button class="primary-btn" type="submit">SIGN IN</button><p class="form-message" id="loginMessage">${safe(msg)}</p></form></div></div></main>`;$('#loginForm').addEventListener('submit',login)}
async function login(e){e.preventDefault();const fd=new FormData(e.currentTarget);const m=$('#loginMessage');m.textContent='Signing in…';const {error}=await supabase.auth.signInWithPassword({email:fd.get('email'),password:fd.get('password')});if(error){m.textContent=error.message;return}if(!(await isAdmin())){await supabase.auth.signOut();loginView('This account is not authorized for the admin area.');return}renderDashboard()}
function shell(){return `<div class="admin-shell"><header class="admin-top"><div class="admin-title">AURENAR / ADMIN</div><div class="admin-actions"><a href="/">VIEW STORE</a><button id="logoutBtn">SIGN OUT</button></div></header><main class="admin-main"><div id="dashboardContent"></div></main></div>`}
async function renderDashboard(){document.body.innerHTML=shell();$('#logoutBtn').addEventListener('click',async()=>{await supabase.auth.signOut();location.reload()});await loadProducts();renderDashboardContent()}
async function loadProducts(){const {data,error}=await supabase.from('products').select('*').order('created_at',{ascending:false});if(error){products=[];console.error(error);return}products=data||[]}
function renderDashboardContent(){const root=$('#dashboardContent');root.innerHTML=`<div class="dashboard"><div class="dashboard-head"><div><p class="eyebrow">STORE CONTROL</p><h1>Products.</h1><p style="color:#777">${products.length} product${products.length===1?'':'s'} in the database.</p></div><div class="admin-actions"><button id="newProduct">ADD PRODUCT</button></div></div><div class="dashboard-grid"><div class="admin-card"><form id="productForm" class="admin-form"><p class="eyebrow">${editingId?'EDIT PRODUCT':'NEW PRODUCT'}</p><label>Product name</label><input id="name" required maxlength="120"><label>Slug</label><input id="slug" required pattern="[a-z0-9-]+" placeholder="white-linen-shirt"><label>Description</label><textarea id="description"></textarea><label>Price (₹)</label><input id="price" required type="number" min="0" step="0.01"><label>Compare-at price (₹)</label><input id="compare" type="number" min="0" step="0.01"><label>Image URL(s)</label><textarea id="images" placeholder="One URL per line"></textarea><p class="image-help">V3 uses image URLs. Supabase Storage upload is intentionally not claimed as connected.</p><label>Sizes</label><input id="sizes" placeholder="S, M, L, XL"><label>Stock</label><input id="stock" required type="number" min="0" step="1"><label class="check-row"><input id="active" type="checkbox"> Active / visible in store</label><button class="primary-btn" type="submit">${editingId?'SAVE CHANGES':'CREATE PRODUCT'}</button><button class="secondary-btn" type="button" id="cancelEdit">CANCEL</button><p class="form-message" id="formMessage"></p></form></div><div class="product-table"><div class="table-head"><span>PRODUCT</span><span>PRICE</span><span>STOCK</span><span>STATUS</span><span>ACTIONS</span></div><div id="productRows"></div></div></div></div>`;$('#newProduct').addEventListener('click',()=>{editingId=null;renderDashboardContent()});$('#cancelEdit').addEventListener('click',()=>{editingId=null;renderDashboardContent()});$('#productForm').addEventListener('submit',saveProduct);renderRows();if(editingId)fillForm(products.find(p=>p.id===editingId))}
function fillForm(p){if(!p)return;$('#name').value=p.name||'';$('#slug').value=p.slug||'';$('#description').value=p.description||'';$('#price').value=p.price??'';$('#compare').value=p.compare_at_price??'';$('#images').value=normalizeImages(p.images).join('\n');$('#sizes').value=(p.sizes||[]).join(', ');$('#stock').value=p.stock??0;$('#active').checked=!!p.is_active}
function renderRows(){const root=$('#productRows');if(!products.length){root.innerHTML='<div class="empty-admin">No products yet. Add the first AURENAR piece.</div>';return}root.innerHTML=products.map(p=>`<div class="admin-product"><img class="admin-preview" src="${safe(normalizeImages(p.images)[0]||'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=200&q=70')}" alt=""><div><strong>${safe(p.name)}</strong><br><span style="color:#777">${safe(p.slug)}</span></div><div>${money(p.price)}</div><div>${p.stock}</div><div><span class="status-pill ${p.is_active?'':'off'}">${p.is_active?'ACTIVE':'INACTIVE'}</span></div><div class="admin-product-actions"><button class="small-btn" data-edit="${safe(p.id)}">EDIT</button><button class="small-btn" data-toggle="${safe(p.id)}">${p.is_active?'DEACTIVATE':'ACTIVATE'}</button><button class="small-btn danger" data-delete="${safe(p.id)}">DELETE</button></div></div>`).join('');$$('[data-edit]',root).forEach(b=>b.addEventListener('click',()=>{editingId=b.dataset.edit;renderDashboardContent()}));$$('[data-toggle]',root).forEach(b=>b.addEventListener('click',()=>toggleActive(b.dataset.toggle)));$$('[data-delete]',root).forEach(b=>b.addEventListener('click',()=>deleteProduct(b.dataset.delete)))}
async function saveProduct(e){e.preventDefault();const m=$('#formMessage');const payload={name:$('#name').value.trim(),slug:$('#slug').value.trim().toLowerCase(),description:$('#description').value.trim()||null,price:Number($('#price').value),compare_at_price:$('#compare').value?Number($('#compare').value):null,images:$('#images').value.split(/\n|,/).map(x=>x.trim()).filter(Boolean),sizes:$('#sizes').value.split(',').map(x=>x.trim()).filter(Boolean),stock:Math.max(0,Number($('#stock').value)||0),is_active:$('#active').checked,updated_at:new Date().toISOString()};if(!payload.name||!payload.slug||payload.price<0){m.textContent='Please enter valid product data.';return}m.textContent='Saving…';let r=editingId?await supabase.from('products').update(payload).eq('id',editingId):await supabase.from('products').insert(payload);if(r.error){m.textContent=r.error.message;return}editingId=null;await loadProducts();renderDashboardContent()}
async function toggleActive(id){const p=products.find(x=>String(x.id)===String(id));if(!p)return;const {error}=await supabase.from('products').update({is_active:!p.is_active,updated_at:new Date().toISOString()}).eq('id',id);if(error){alert(error.message);return}await loadProducts();renderDashboardContent()}
async function deleteProduct(id){if(!confirm('Delete this product permanently from the database?'))return;const {error}=await supabase.from('products').delete().eq('id',id);if(error){alert(error.message);return}await loadProducts();renderDashboardContent()}
supabase.auth.onAuthStateChange(async()=>{if(location.pathname.startsWith('/admin')){setTimeout(async()=>{if(await isAdmin())renderDashboard();},0)}});(async()=>{if(await isAdmin())renderDashboard();else loginView()})();
