import {supabase} from "./supabase.js";
const fallback=[{id:"demo1",name:"White Linen Shirt",price:1499,images:[],sizes:["S","M","L","XL"],stock:10,description:"A clean linen essential."},{id:"demo2",name:"Noir Overshirt",price:1899,images:[],sizes:["S","M","L","XL"],stock:10,description:"A structured everyday layer."},{id:"demo3",name:"Stone Trousers",price:1799,images:[],sizes:["30","32","34","36"],stock:10,description:"Relaxed tailored trousers."}];
let products=[],cart=JSON.parse(localStorage.getItem("aurenar_cart")||"[]");
const money=n=>"₹"+Number(n||0).toLocaleString("en-IN");const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));const save=()=>localStorage.setItem("aurenar_cart",JSON.stringify(cart));
async function load(){try{let r=await supabase.from("products").select("*").eq("is_active",true).order("created_at",{ascending:false});if(r.error)throw r.error;products=r.data||[]}catch(e){products=[]}if(!products.length)products=fallback;render()}
function img(p){let u=Array.isArray(p.images)?p.images[0]:"";return u?`<img src="${esc(u)}" alt="${esc(p.name)}" loading="lazy">`:`<div class="placeholder">AURENAR</div>`}
function render(){$("products").innerHTML=products.map(p=>`<article><a href="/product.html?id=${encodeURIComponent(p.id)}"><div class="photo">${img(p)}</div></a><div class="info"><div class="name">${esc(p.name)}</div><div class="price">${money(p.price)}</div><button class="cardbtn" data-add="${p.id}" ${Number(p.stock)<=0?"disabled":""}>${Number(p.stock)<=0?"OUT OF STOCK":"ADD TO BAG"}</button></div></article>`).join("");$("count").textContent=cart.reduce((a,x)=>a+x.qty,0);$("status").textContent=products.length+" pieces";renderBag()}
function add(id){let p=products.find(x=>String(x.id)===String(id));if(!p||p.stock<=0)return;let x=cart.find(x=>String(x.id)===String(id));x?x.qty++:cart.push({id:p.id,qty:1});save();render();open("bagDrawer")}
function renderBag(){let total=0;if(!cart.length){$("bagBody").innerHTML="<p class='msg'>Your bag is empty.</p>";return}$("bagBody").innerHTML=cart.map(x=>{let p=products.find(y=>String(y.id)===String(x.id));if(!p)return"";total+=p.price*x.qty;return`<div class="bagrow"><div>${esc(p.name)}<br><span class="msg">${money(p.price)} × ${x.qty}</span></div><div><button data-q="${p.id}" data-d="-1">−</button> ${x.qty} <button data-q="${p.id}" data-d="1">+</button></div></div>`}).join("")+`<p>Total: <b>${money(total)}</b></p><button class="primary" id="checkout">CHECKOUT</button>`}
function open(id){$(id).classList.add("open");$("overlay").classList.add("open")}function close(){document.querySelectorAll(".drawer").forEach(x=>x.classList.remove("open"));$("overlay").classList.remove("open")}
function $(id){return document.getElementById(id)}
document.addEventListener("click",e=>{let a=e.target.closest("[data-add]");if(a)add(a.dataset.add);let q=e.target.closest("[data-q]");if(q){let x=cart.find(x=>String(x.id)===String(q.dataset.q));if(x){x.qty+=Number(q.dataset.d);if(x.qty<1)cart=cart.filter(y=>y!==x);save();render()}}if(e.target.id==="bag")open("bagDrawer");if(e.target.id==="closeBag"||e.target.id==="closeAccount"||e.target.id==="overlay")close();if(e.target.id==="account"){$("accountBody").innerHTML="<p class='msg'>Customer authentication is available through Supabase Auth. Admin access is separate and requires the admin role.</p>";open("accountDrawer")}if(e.target.id==="checkout")location.href="/checkout.html"});load();
