-- AURENAR V3 — run this in Supabase SQL Editor.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'customer' check (role in ('customer','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(10,2) not null default 0,
  image_url text,
  category text not null default 'men',
  sizes text[] not null default array['S','M','L','XL'],
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.products enable row level security;

drop policy if exists "public read active products" on public.products;
create policy "public read active products" on public.products
for select using (is_active = true);

drop policy if exists "admin full product access" on public.products;
create policy "admin full product access" on public.products
for all using (
  exists (select 1 from public.profiles p where p.id=auth.uid() and p.role='admin')
) with check (
  exists (select 1 from public.profiles p where p.id=auth.uid() and p.role='admin')
);

drop policy if exists "users read own profile" on public.profiles;
create policy "users read own profile" on public.profiles
for select using (id=auth.uid());

-- After creating your admin user in Supabase Auth, run:
-- insert into public.profiles (id, role) values ('YOUR_AUTH_USER_UUID','admin')
-- on conflict (id) do update set role='admin';
